### ISSUE TITLE
Does not work on RHEL

### ISSUE THREAD

**Issue by smapjb** [dockpack/base_postgres#5]
The "centos" hard coded in this url needs to be "redhat" for RHEL proper.

https://github.com/dockpack/base_postgres/blob/dc75a8aea3427e841a4b1df826d99e64e7ab2659/defaults/main.yml#L11

Also EPEL repo needs to be installed/enabled to pull python-pip

**Comment by bbaassssiiee** [comment]
> As of 15 April 2019, there is only one repository RPM per distro, and it includes repository information for all available PostgreSQL releases.
